g

diff --git a/.github/workflows/solutionPackageValidation.yaml b/.github/workflows/solutionPackageValidation.yaml
--- a/.github/workflows/solutionPackageValidation.yaml
+++ b/.github/workflows/solutionPackageValidation.yaml
@@ -52,24 +52,24 @@ jobs:
         
         
         
-        run: |
-          if ! git remote | grep -q origin; then
-            echo "Remote 'origin' not found. Adding it..."
-            git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Tintintani/Solution-Validation.git
-          else
-            echo "Remote 'origin' already exists."
-          fi
+      #   run: |
+      #     if ! git remote | grep -q origin; then
+      #       echo "Remote 'origin' not found. Adding it..."
+      #       git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Tintintani/Solution-Validation.git
+      #     else
+      #       echo "Remote 'origin' already exists."
+      #     fi
 
-      - name: Get Modified Files
-        run: |
-          git fetch origin
-          git diff --name-only origin/master ${{ github.events.pull_request.head.sha }} > changedFiles.txt
-          ls
+      # - name: Get Modified Files
+      #   run: |
+      #     git fetch origin
+      #     git diff --name-only origin/master ${{ github.events.pull_request.head.sha }} > changedFiles.txt
+      #     ls
       
-      - name: Install dependencies
-        run: |
-              python -m pip install --upgrade pip
-              pip install python-dotenv
-      - name: Run Script
-        run: |
-          python run.py  
+      # - name: Install dependencies
+      #   run: |
+      #         python -m pip install --upgrade pip
+      #         pip install python-dotenv
+      # - name: Run Script
+      #   run: |
+      #     python run.py  
