initial commit

diff --git a/.github/workflows/solutionPackageValidation.yaml b/.github/workflows/solutionPackageValidation.yaml
--- a/.github/workflows/solutionPackageValidation.yaml
+++ b/.github/workflows/solutionPackageValidation.yaml
@@ -1,12 +1,13 @@
 name: Solution Package Validations
-permissions:
-  contents: write
+
 on: 
   pull_request:
     branches:
       - master
     paths:
-      - 'Solutions/**'
+      - 'Solutions/**/Package/mainTemplate.json'
+      - 'Solutions/**/Package/createUiDefinition.json'
+
     # Allows to run workflow manually from the Actions tab
     workflow_dispatch:
 jobs:
@@ -17,10 +18,33 @@ jobs:
       - name: Chekout pull request braanch
         uses: actions/checkout@v2
         with:
-          fetch-depth: 0 
+          # ref: ${{github.event.pull_request.head.ref}}
+          # repository: ${{github.event.pull_request.head.repo.full_name}}
+          # persist-credentials: false 
+          fetch-depth: 0
+      - name: Check and add origin remote
+        run: |
+          if ! git remote | grep -q origin; then
+            echo "Remote 'origin' not found. Adding it..."
+            git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Tintintani/Solution-Validation.git
+          else
+            echo "Remote 'origin' already exists."
+          fi
+
       - name: Get Modified Files
         run: |
           git fetch origin master:refs/remotes/origin/master
-          git diff --name-only origin/master ${{ github.events.pull_request.head.sha }} > changed_files.txt
-          echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_ENV
-          cat changed_files.txt
+          git diff --name-only origin/master ${{ github.events.pull_request.head.sha }} > changedFiles.txt
+          echo "CHANGED_FILES = $(cat changedFiles.txt)" >> $GITHUB_ENV
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
+        run: |
+              python -m pip install --upgrade pip
+              pip install os
+              pip install dotenv
+      - name: Run Script
+        run: |
+          python run.py  
